### ISSUE TITLE
Fatal error: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by DamianMullins** [TryKickoff/statix#3]
When running the `grunt serve` task I am presented with the following:

``` bash
Running "imagemin:grunticon" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined
```

Anyone else see this?

After some research online I think it's possibly related to the version of `grunt-contrib-imagemin` which is in use?

I'll test with updated package.

**Comment by DamianMullins** [comment]
Updating `grunt-contrib-imagemin` to 1.0.0 fixes the issue for me. I'll create a pull request for you guys to review.

**Comment by mrmartineau** [comment]
Hi @DJMelonz, thanks for the PR. This is a known issue which was fixed in the main [kickoff repo](https://github.com/TryKickoff/kickoff/issues/65) but may not have made it to this one..

**Comment by DamianMullins** [comment]
Hey @mrmartineau, no worries. [PR is open here](https://github.com/TryKickoff/statix/pull/4) in any case :smile:

**Comment by ashleynolan** [comment]
Have just merged this into master – cheers for the spot.  Hoping to work on updating the repo next week to bring it in line with the latest version of Kickoff.
