### ISSUE TITLE
Statix 'next' version

### ISSUE THREAD

**Issue by rentorm** [TryKickoff/statix#8]
Just a general question, how do we organize versions for releases?

Current code and setup in 'next' branch will be v4 or v5?

Looking at v4 (https://github.com/TryKickoff/statix/issues/5) todo list, looks like most of it no longer relevant as we started to use Gulp setup from latest Kickoff version.

I guess we need to set up a new 'update plan' for the next release of Statix

**Comment by ashleynolan** [comment]
Yeh, you’re exactly right.  I’ll take a look at that list and see what’s still relevant now that we’ve moved onto gulp.

The next major release will be tagged at v4 – don’t think we’re far away from being able to release now after your update.

**Comment by ashleynolan** [comment]
Have updated the release plan in #5 – closing this issue as anything relating to the new release should be kept there.
